service:
  name: pagerduty-slack

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs8.10

functions:
  command:
    handler: src/index.pagerduty
    events:
      - http:
          method: post
          path: /slack-command
